### ISSUE TITLE
diff(nil) should not raise RecordNotFound

### ISSUE THREAD

**Issue by eiked** [tim/activerecord-diff#6]
foo.diff(nil)

results in:

ActiveRecord::RecordNotFound: Couldn't find Foo without an ID
from /opt/local/lib/ruby2.1/gems/2.1.0/gems/activerecord-4.1.6/lib/active_record/relation/finder_methods.rb:411:in `find_with_ids'

Instead 
- it should either raise an IllegalArgument Exception early (argument to diff can not be nil)

- or should return all fields as diff (the diff[1] being nil)

I'd suggest the second behaviour

**Comment by tim** [comment]
Calling diff with nil is equivalent to calling diff without arguments, which is well defined: it returns the differences between the object and the corresponding database record. Calling diff with nil on a new/unsaved object is fairly meaningless as there's nothing to diff against. Easy fix: don't call diff(nil) on an unsaved object.
