### ISSUE TITLE
diff should have options

### ISSUE THREAD

**Issue by eiked** [tim/activerecord-diff#7]
The diff DSL is fine

    diff :attr1, :attr2

but it would be nnice to specify options per call:

    foo.diff(other, attributes:[:attr1, attr2])

Maybe it should even support a block for comparison, I suggest:

    foo.diff(other){|key, obj, other|}

which is more flexible than:

    foo.diff(other){|key, value, other_value|}

Very good gem!
~eike

**Comment by tim** [comment]
Can you share more about your use cases, i.e. some code examples of what you're trying to do?
